name: newsfeed_2
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/icons/icon_comment.png
    - assets/icons/icon_heart.png
    - assets/icons/icon_heart_filled.png
    - assets/icons/icon_home.png
    - assets/icons/icon_home_enclosed.png
    - assets/icons/icon_person.png
    - assets/icons/icon_plus.png
    - assets/icons/icon_back_arrow.png
    - assets/icons/icon_vertical_ellipse.png
    - assets/mock/profile_pictures/profile_harry.jpg
    - assets/mock/profile_pictures/profile_robert.jpg
    - assets/mock/profile_pictures/profile_tess.jpg
    - assets/mock/profile_pictures/profile_tim.jpg
    - assets/mock/profile_pictures/profile_cat.jpg
    - assets/mock/profile_pictures/profile_corey.jpg
    - assets/mock/profile_pictures/profile_albie.jpg
    - assets/mock/profile_pictures/profile_jo.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
  #
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 200
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 500
    - family: Source Sans
      fonts:
        - asset: assets/fonts/source_sans/SourceSansPro-Light.ttf
          weight: 200
        - asset: assets/fonts/source_sans/SourceSansPro-Regular.ttf
          weight: 300
        - asset: assets/fonts/source_sans/SourceSansPro-Semibold.ttf
          weight: 400
        - asset: assets/fonts/source_sans/SourceSansPro-Bold.ttf
          weight: 500
